<?xml version="1.0"?>
<robot  xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find rl_fra2mo_description)/urdf/utility_macro.xacro" />

  <!-- WHOLE BASE MACRO-->
  <xacro:macro name="fra2mo_base" > <!--fb : front, back ; lr: left, right -->

    <!-- Base properties -->
    <xacro:property name="base_height" value="0.180" /> 
    <xacro:property name="base_radius" value="0.11" /> 
    <xacro:property name="base_mass" value="5" />
    <xacro:property name="wheel_mass" value="2.5" />
    <xacro:property name="wheel_radius" value="0.035" /> 
    <xacro:property name="wheel_axle" value="0.130" /> 
   
    <!-- Actual body/chassis of the robot -->
    <link name="base_footprint">
    </link>

    <link name="base_link">
      <!-- Inertial properties -->
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="${base_mass}" />
        <xacro:cylinder_inertia m="${base_mass}" r="${base_radius}" h="${base_height}" />
      </inertial>
      <!-- Visual representation -->
      <visual> 
        <geometry>
          <mesh filename="file://$(find rl_fra2mo_description)/meshes/rl_fra2mo_body.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="Blue" />
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <!-- Collision properties -->
      <collision>
        <geometry>
          <cylinder length="${base_height}" radius="${base_radius}" />
        </geometry>
        <origin xyz="0 0.0 ${(base_height/2.0)-0.05}" rpy="0 0 0" />
      </collision> 
      <collision>
        <geometry>
          <sphere radius="0.019" />
        </geometry>
        <origin xyz="-0.0825 0.0 -0.04" rpy="0 0 0" />
      </collision>       
    </link>

    <!-- Left Wheel -->
    <link name="left_wheel_link">
      <visual> 
        <geometry>
          <mesh filename="file://$(find rl_fra2mo_description)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="Black" />
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision> 
        <geometry>
          <mesh filename="file://$(find rl_fra2mo_description)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="${wheel_mass}" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
    </link>

    <!-- Right Wheel -->
    <link name="right_wheel_link">
      <visual> 
        <geometry>
          <mesh filename="file://$(find rl_fra2mo_description)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="Black"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision> 
        <geometry>
          <mesh filename="file://$(find rl_fra2mo_description)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="${wheel_mass}" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
    </link>

    <!-- Additional Links -->
    <link name="d435_link" />
    <link name="lidar_link" />

    <!-- Joints -->
    <joint name="base_footprint_joint" type="fixed">
      <parent link="base_footprint" />
      <child link="base_link" />
      <origin xyz="0.0 0.0 0.059" rpy="0 0 0" />
    </joint>
    <joint name="left_wheel_joint" type="continuous">
      <parent link="base_link" />
      <child link="left_wheel_link" />
      <origin xyz="0.04025 0.062 -0.024" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <limit effort="100" velocity="100" />
      <dynamics damping="0.5" friction="0.01" />
    </joint>
    <joint name="right_wheel_joint" type="continuous">
      <parent link="base_link" />
      <child link="right_wheel_link" />
      <origin xyz="0.04025 -0.062 -0.024" rpy="0 0 ${-M_PI}" />
      <axis xyz="0 -1 0" />
      <limit effort="100" velocity="100" />
      <dynamics damping="0.5" friction="0.01" />
    </joint>
    <joint name="d435_joint" type="fixed">
      <parent link="base_link" />
      <child link="d435_link" />
      <origin xyz="0.090925 0.0 0.06670" rpy="0 0 0" />
    </joint>
    <joint name="lidar_joint" type="fixed">
      <parent link="base_link" />
      <child link="lidar_link" />
      <origin xyz="0.0 0.0 0.125" rpy="0 0 0" />
    </joint>

    <!-- Gazebo Material Assignments 
    <gazebo reference="base_link">
      <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="left_wheel_link">
      <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="right_wheel_link">
      <material>Gazebo/Black</material>
    </gazebo>-->

    <!-- Transmissions 
    <transmission name="left_wheel_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="left_wheel_joint" />
      <actuator name="left_wheel_joint_motor">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </actuator>
    </transmission>
    <transmission name="right_wheel_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="right_wheel_joint" />
      <actuator name="right_wheel_joint_motor">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </actuator>
    </transmission>-->

    <!-- Plugin for differential drive control in Gazebo 
    <gazebo>
      <plugin name="gazebo_ros_diff_drive" filename="libgazebo_ros_diff_drive.so" >
        <ros>
          <namespace>/</namespace>
          <remapping>cmd_vel:=/cmd_vel</remapping>
        </ros>
        <update_rate>100.0</update_rate>
        <left_joint>left_wheel_joint</left_joint>
        <right_joint>right_wheel_joint</right_joint>
        <wheel_separation>${wheel_axle}</wheel_separation>
        <wheel_diameter>${2*wheel_radius}</wheel_diameter>
        <max_wheel_torque>30</max_wheel_torque>
        <max_wheel_acceleration>1.8</max_wheel_acceleration>
        <odom_frame>odom</odom_frame>
        <robot_base_frame>base_footprint</robot_base_frame>
        <cmd_vel_topic>cmd_vel</cmd_vel_topic>
        <odometry_topic>odom</odometry_topic>
        <publish_joint_states>true</publish_joint_states>
      </plugin>
    </gazebo>-->

  </xacro:macro>
</robot>

